name: linting, testing, building
run-name: ci pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: linting ts
        run: npm run lint-check
      - name: linting scss
        run: npm run stylelint-check
      - name: unit testing
        run: npm run test
      - name: build production project
        run: npm run build:prod
